/**
 * Community Pulse Report
 * Collects recent messages, analyses them with OpenAI, and posts a
 * structured sentiment summary embed to the staff channel.
 * Runs independently at 17:00 CET — existing reports are unaffected.
 */

import { EmbedBuilder } from 'discord.js';
import { config } from '../config';
import { logger } from '../logger';
import { collectRecentMessages } from '../collectors/messageCollector';
import { analyseCommunityPulse } from '../api/openai';
import { postDailyReport } from '../api/discord';
import { insertSentimentReport } from '../store/db';
import { formatDate } from './formatters';

export async function runSentimentReport(): Promise<void> {
  // ── Precondition checks ────────────────────────────────────────────────────
  if (!config.openAiApiKey) {
    logger.warn('[sentiment] OPENAI_API_KEY not set — Community Pulse report skipped');
    return;
  }
  if (config.sentimentChannelIds.length === 0) {
    logger.warn('[sentiment] SENTIMENT_CHANNEL_IDS not configured — Community Pulse report skipped');
    return;
  }

  logger.info('[sentiment] Starting Community Pulse report...');

  // ── Collect messages (last 24 hours) ──────────────────────────────────────
  const messages = await collectRecentMessages(config.sentimentChannelIds);

  if (messages.length < 10) {
    logger.warn(`[sentiment] Only ${messages.length} messages found — not enough data, skipping`);
    return;
  }

  // ── Analyse with OpenAI ────────────────────────────────────────────────────
  const pulse = await analyseCommunityPulse(messages);
  if (!pulse) {
    logger.error('[sentiment] OpenAI analysis failed — Community Pulse report not posted');
    return;
  }

  // ── Persist to DB ──────────────────────────────────────────────────────────
  const takenAt = new Date().toISOString();
  insertSentimentReport(takenAt, pulse.mood, JSON.stringify(pulse));

  // ── Build embed ────────────────────────────────────────────────────────────
  const today = formatDate(new Date());

  const topicsText     = pulse.topics.map(t => `• ${t}`).join('\n')      || '_Nothing notable_';
  const painText       = pulse.pain_points.map(p => `• ${p}`).join('\n') || '_Nothing notable_';
  const positivesText  = pulse.positives.map(p => `• ${p}`).join('\n')   || '_Nothing notable_';

  const embed = new EmbedBuilder()
    .setTitle(`💬 Community Pulse — ${today}`)
    .setColor(0x9B59B6)
    .setDescription(`AI-generated summary of recent player discussion *(${messages.length} messages sampled)*`)
    .addFields(
      {
        name:   '📌 Top Topics',
        value:  topicsText,
        inline: false,
      },
      {
        name:   '😤 Pain Points',
        value:  painText,
        inline: true,
      },
      {
        name:   '😊 Positives',
        value:  positivesText,
        inline: true,
      },
      {
        name:   '🌡️ Mood',
        value:  pulse.mood,
        inline: false,
      },
    )
    .setFooter({ text: 'WoWS Community Reports · AI-generated by OpenAI' })
    .setTimestamp();

  // ── Post ───────────────────────────────────────────────────────────────────
  // Reuse postDailyReport since it posts to the same staff channel
  await postDailyReport(embed);
  logger.info('[sentiment] Community Pulse report posted');
}
