/**
 * Community Pulse Report
 * Collects recent messages, analyses them with OpenAI, and posts a
 * structured sentiment summary embed to the staff channel.
 * Runs independently at 17:00 CET — existing reports are unaffected.
 */

import { EmbedBuilder } from 'discord.js';
import { config } from '../config';
import { logger } from '../logger';
import { queryIndexedMessages } from '../store/messageDb';
import { getSetting } from '../store/settingsDb';
import { collectRecentMessages } from '../collectors/messageCollector';
import { analyseCommunityPulse } from '../api/openai';
import { postDailyReport } from '../api/discord';
import { insertSentimentReport } from '../store/db';
import { formatDate } from './formatters';

export type SentimentSource = 'db' | 'live';

export async function runSentimentReport(source: SentimentSource = 'db'): Promise<void> {
  // ── Precondition checks ────────────────────────────────────────────────────
  if (!config.openAiApiKey) {
    logger.warn('[sentiment] OPENAI_API_KEY not set — Community Pulse report skipped');
    return;
  }
  // Read channels + limit from settings DB (falls back to env var defaults)
  const channelIds = getSetting('sentiment_channel_ids', config.sentimentChannelIds.join(','))
    .split(',').map(s => s.trim()).filter(Boolean);
  const messageLimit = parseInt(
    getSetting('sentiment_message_limit', String(config.sentimentMessageLimit)), 10,
  );

  if (channelIds.length === 0) {
    logger.warn('[sentiment] No sentiment channels configured — Community Pulse report skipped');
    return;
  }

  logger.info(`[sentiment] Starting Community Pulse report (source: ${source})...`);

  // ── Collect messages ───────────────────────────────────────────────────────
  // 'db'   → reads from the on-disk SQLite index (fast, same as /api/chat)
  // 'live' → paginates the Discord REST API in real-time (slower but fresh)
  const messages = source === 'live'
    ? await collectRecentMessages(channelIds)
    : queryIndexedMessages(24, channelIds, messageLimit, []);

  if (messages.length < 10) {
    logger.warn(`[sentiment] Only ${messages.length} messages found — not enough data, skipping`);
    return;
  }

  // ── Analyse with OpenAI ────────────────────────────────────────────────────
  const pulse = await analyseCommunityPulse(messages);
  if (!pulse) {
    logger.error('[sentiment] OpenAI analysis failed — Community Pulse report not posted');
    return;
  }

  // ── Persist to DB ──────────────────────────────────────────────────────────
  const takenAt = new Date().toISOString();
  insertSentimentReport(takenAt, pulse.mood, JSON.stringify(pulse));

  // ── Build embed ────────────────────────────────────────────────────────────
  const today = formatDate(new Date());

  const topicsText    = pulse.topics.map(t => `• ${t.text}`).join('\n')      || '_Nothing notable_';
  const painText      = pulse.pain_points.map(p => `• ${p.text}`).join('\n') || '_Nothing notable_';
  const positivesText = pulse.positives.map(p => `• ${p.text}`).join('\n')   || '_Nothing notable_';

  const moodScore  = Math.min(5, Math.max(1, Math.round(pulse.mood_score ?? 3)));
  const moodBar    = '█'.repeat(moodScore) + '░'.repeat(5 - moodScore);
  const moodColour = moodScore >= 4 ? 0x2ECC71 : moodScore <= 2 ? 0xE74C3C : 0x9B59B6;

  const embed = new EmbedBuilder()
    .setTitle(`💬 Community Pulse — ${today}`)
    .setColor(moodColour)
    .setDescription(`AI-generated summary of recent player discussion *(${messages.length} messages analysed)*`)
    .addFields(
      {
        name:   '📌 Top Topics',
        value:  topicsText,
        inline: false,
      },
      {
        name:   '😤 Pain Points',
        value:  painText,
        inline: true,
      },
      {
        name:   '😊 Positives',
        value:  positivesText,
        inline: true,
      },
      {
        name:   '🔥 Trending Today',
        value:  pulse.trending || '_Nothing unusually trending_',
        inline: false,
      },
      {
        name:   `🌡️ Mood — ${moodScore}/5  ${moodBar}`,
        value:  pulse.mood,
        inline: false,
      },
    )
    .setFooter({ text: 'WoWS Community Reports · AI-generated by OpenAI' })
    .setTimestamp();

  // ── Post ───────────────────────────────────────────────────────────────────
  // Reuse postDailyReport since it posts to the same staff channel
  await postDailyReport(embed);
  logger.info('[sentiment] Community Pulse report posted');
}
